### ISSUE TITLE
mapbox style

### ISSUE THREAD

**Issue by Nassiming** [ddiu8081/bus-vis#4]
The map configuration is beautiful, is it convenient to public the mapbox style?

**Comment by ddiu8081** [comment]
Yeah, the style url is:

```
mapbox://styles/ddiu8081/ckz82q8eb000c14o8uw4ky79d
```

and can be found in `src/data/dataList.ts`.

sharable url: 

```
https://api.mapbox.com/styles/v1/ddiu8081/ckz82q8eb000c14o8uw4ky79d.html?title=copy&access_token=pk.eyJ1IjoiZGRpdTgwODEiLCJhIjoiY2o5cjQzMDE3NjVxZjJxbXFhNDRmbmk5biJ9.ywNQKxtepoX5HnSs6xW22Q&zoomwheel=true&fresh=true#11.39/39.9397/116.4456
```

But I think it is almost the same as the official theme [Mapbox Light](https://www.mapbox.com/maps/light), only with some components hidden :)
